refs: http://c.biancheng.net/numpy/

In [3]:
import numpy as np

### 一、创建数组

#### 1.1 创建数组API
* numpy.empty(shape, dtype = float, order = 'C')
* numpy.zeros(shape, dtype=float, order="C")
* numpy.ones(shape, dtype=None, order='C')
* numpy.asarray(sequence, dtype=None, order=None)
    * sequence: python列表或元组
* numpy.fromiter(iterable, dtype, count=-1)
    * iterable: 可迭代对象
    * count: 读取的数据数量，默认为 -1，读取所有数据

In [8]:
list=range(6)
i=iter(list)
#使用i迭代器，通过fromiter方法创建ndarray
array=np.fromiter(i, dtype=float)
print(array)

[0. 1. 2. 3. 4. 5.]


#### 1.2 创建数组区间API
* numpy.arange(start, stop, step, dtype)
* np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) 创建等差数列
    * start：代表数值区间的起始值
    * stop：代表数值区间的终止值
    * num：表示数值区间内要生成多少个均匀的样本。默认值为 50
    * endpoint：默认为 True，表示数列包含 stop 终止值，反之不包含
    * retstep：默认为 True，表示生成的数组中会显示公差项，反之不显示
    * dtype：代表数组元素值的数据类型
* np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None) 创建等比数列
    * start	序列的起始值：base start
    * stop	序列的终止值：base stop
    * num	数值范围区间内样本数量，默认为 50
    * endpoint	默认为 True 包含终止值，反之不包含
    * base	对数函数的 log 底数，默认为10
    * dtype	可选参数，指定 ndarray 数组的数据类型

In [10]:
a = np.linspace(1,10,10)
print(a)

a = np.logspace(1, 2, num=10)
print (a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


#### 1.2 创建随机数组
* np.random.random((1, 2)) 生成0 1 均匀分布的数组
* np.random.rand(1, 2) 和random相同，格式稍有区别
* np.random.randn(1, 2) 正态分布，输入为维度
* randint(low, high=None, size=None, dtype=int) 给定上下范围的随机数

#### 1.3 定义结构化数据

In [4]:
teacher = np.dtype([('name','S20'), ('age', 'i1'), ('salary', 'f4')])
#输出结构化数据teacher
print(teacher)
#将其应用于ndarray对象
b = np.array([('ycs', 32, 6357.50),('jxe', 28, 6856.80)], dtype = teacher) 
print(b)

[('name', 'S20'), ('age', 'i1'), ('salary', '<f4')]
[(b'ycs', 32, 6357.5) (b'jxe', 28, 6856.8)]


#### 1.4 数组属性
* ndarray.ndim 获取数组维度
* ndarray.itemsize 返回数组中每个元素的大小（以字节为单位）
* ndarray.flags 返回 ndarray 数组的内存信息

In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.itemsize)
print(a.flags)

2
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### 二、数组操作

#### 2.1 索引和切片

In [26]:
a = np.arange(10)
print(a[2:9:3]) # 可以设置间隔

x = np.array([[1,  2],  [3,  4],  [5,  6]])
print(x[(0,1,2),(0,1,0)] ) # 索引组合

x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
print (x[x > 6]) # 布尔索引

a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a[~np.isnan(a)]) # is nan

x=np.arange(32).reshape((8,4))
print(x[[4,2,1,7]]) # 分别对应 第4行数据、第2行数据、第1行数据、第7行数据项，参考这里，x[2:4]中间是生成列表？

[2 5 8]
[1 4 5]
[ 7  8  9 10 11]
[1. 2. 3. 4. 5.]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


#### 2.2 遍历数组
在内存中，Numpy 数组提供了两种存储数据的方式，分别是 C-order（行优先顺序）与 Fortrant-order（列优先顺序），默认为行优先
* np.nditer(): **按内存顺序遍历**

In [46]:
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('case1:')
for x in np.nditer(a):
   print(x, end=' ')
print('\ncase2:')
for x in np.nditer(a.T):
   print(x, end=' ')
print('\ncase3:')
for x in np.nditer(a.T.copy()):
    print(x, end=' ')
print('\ncase4:')
for x in np.nditer(a, order = 'F'):
    print(x, end=' ')
print('\n遍历多个数组:')
a = np.arange(0,60,5).reshape(3,4)
b = np.arange(12).reshape(3,4)
print(a)
print(b)
for x,y in np.nditer([a,b]):
    print(f'{x}:{y},', end=" ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
case1:
0 5 10 15 20 25 30 35 40 45 50 55 
case2:
0 5 10 15 20 25 30 35 40 45 50 55 
case3:
0 20 40 5 25 45 10 30 50 15 35 55 
case4:
0 20 40 5 25 45 10 30 50 15 35 55 
遍历多个数组:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0:0, 5:1, 10:2, 15:3, 20:4, 25:5, 30:6, 35:7, 40:8, 45:9, 50:10, 55:11, 

#### 2.3 常用操作
##### 2.3.1 迭代
* ndarray.flat 遍历迭代器，与上面不同，他是array类的元素
* ndarray.flatten 返回一维形式的数组副本
* ndarray.ravel 返回一维形式的数组视图

##### 2.3.2 换轴
* numpy.transpose(arr), ndarray.T 转置
* numpy.swapaxes(arr, axis1, axis2) 交换轴
* numpy.rollaxis(arr, axis, start) 滚动轴 **慎用**

##### 2.3.3 变维
* ndarray.reshape 不改变原数组
* ndarray.resize 改变原数组
* numpy.expand_dims(arr, axis) 在axis处插入新轴
* numpy.squeeze() 删除维度为1的轴

##### 2.3.4 连接与分割
* 连接
    * numpy.concatenate((a1, a2, ...), axis) 沿指定轴连接两个或者多个相同形状的数组
    * stack     沿着新的轴连接一系列数组
    * hstack	  按水平顺序堆叠序列中数组（列方向）
    * vstack	  按垂直方向堆叠序列中数组（行方向）
* 分割
    * numpy.split(ary, indices_or_sections, axis) 将一个数组分割为多个子数组
        * ary：被分割的数组
        * indices_or_sections：若是一个整数，代表用该整数平均切分，若是一个数组，则代表沿轴切分的位置（左开右闭
        * axis：默认为0，表示横向切分；为1时表示纵向切分
    * stack     沿着新的轴连接一系列数组
    * hstack	  按水平顺序堆叠序列中数组（列方向）
    * vstack	  按垂直方向堆叠序列中数组（行方向）
 
##### 2.3.5 数组增减
* numpy.append(arr, values, axis=None)
* numpy.insert(arr, obj, values, axis)
* numpy.delete(arr, obj, axis)
* numpy.unique(arr, return_index, return_inverse, return_counts) 
    * arr：输入数组，若是多维数组则以一维数组形式展开
    * return_index：如果为 True，则返回新数组元素在原数组中的位置（索引）
    * return_inverse：如果为 True，则返回原数组元素在新数组中的位置（索引）
    * return_counts：如果为 True，则返回去重后的数组元素在原数组中出现的次数

In [57]:
x = np.arange(6).reshape(2,3)
print(x)
#返回所有大于1的元素索引
y=np.argwhere(x)
print(y)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]


#### 2.4 统计函数
* numpy.amin(axis)， numpy.amax()沿指定轴寻找最值
* numpy.argmax()， numpy.argmin() 返回索引
* numpy.ptp(axis) 计算极差
* numpy.percentile(a, q, axis) 百分位数
* numpy.median(axis)中位数
* numpy.mean() 平均数
* np.average(,weights) 加权平均数
* np.var() 方差
* np.std() 标准差

* numpy.sort(， axis) 排序，返回副本
* numpy.argsort(， axis) 排序 返回索引

* numpy.nonzero() 非零元素的索引位置
* numpy.where() 返回满足元素的索引
* numpy.argwhere() 返回非0元索引
* numpy.argwhere(ndarray > x) 返回大于x的索引
* numpy.extract() 返回值是满足了给定条件的元素值

#### 2.5 矩阵操作
* np.eye(m, n) m * n对角元为1的矩阵
* numpy.identity(n) n截单位矩阵

* numpy.dot() 向量返回内积，矩阵返回矩阵积
* numpy.vdot() 向量内积
* numpy.matmul() 矩阵积
* np.linalg.det() 行列式
* numpy.linalg.inv() 逆矩阵
* np.linalg.eig() 特征值和特征向量

In [91]:
mat = np.array([[-1, 1, 0],
              [-4, 3, 0],
              [1, 0, 2]])

eigenvalue, featurevector = np.linalg.eig(mat)

print("特征值：", eigenvalue)
print("特征向量：", featurevector)

特征值： [2. 1. 1.]
特征向量： [[ 0.          0.40824829  0.40824829]
 [ 0.          0.81649658  0.81649658]
 [ 1.         -0.40824829 -0.40824829]]


### 三、函数库
#### 3.1 位操作
* numpy.bitwise_and  &   计算数组元素之间的按位与运算
* numpy.bitwise_or	 |	  计算数组元素之间的按位或运算
* numpy.invert	    ~   计算数组元素之间的按位取反运算
* numpy.left_shift	 <<	  将二进制数的位数向左移
* numpy.right_shift	 >>	  将二进制数的位数向右移

#### 3.2 数学运算
##### 3.2.1 三角函数
**默认为弧度制** 
* numpy.pi
* numpy.sin() cos tan
* numpy.arcsin() arcos arctan
* numpy.degrees() 转化为角度

##### 3.2.2 四舍五入
* numpy.around(a,decimals=0) 四舍五入，decimals为小数位数
* numpy.floor() 向下取整
* numpy.ceil() 向上取整

##### 3.2.3 复数操作
* numpy.real() 返回复数数组的实部
* numpy.imag() 返回复数数组的虚部
* numpy.conj() 通过更改虚部的符号，从而返回共轭复数
* numpy.angle() 返回复数参数的角度，该函数的提供了一个 deg 参数，如果  deg=True，则返回的值会以角度制来表示，否则以以弧度制来表示

In [65]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j])
print(a)
print(np.real(a), a.real)
print(np.imag(a), a.imag)
print(np.conj(a), a.conj)
print(np.angle(a))
print(np.angle(a, deg = True))

[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
[-0.  0. 11.  1.] [-0.  0. 11.  1.]
[-5.6  0.2  0.   1. ] [-5.6  0.2  0.   1. ]
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ] <built-in method conj of numpy.ndarray object at 0x0000019307712850>
[-1.57079633  1.57079633  0.          0.78539816]
[-90.  90.   0.  45.]
