## 1、模型参数打印

In [1]:
import torch
from torch import nn
import torch.nn.functional as F

### 1.1 创建模型

In [18]:
net = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 1))

X = torch.rand(size=(2, 4))
y = net(X)
print(y)
print(type(net))
print(net)

tensor([[0.4218],
        [0.6000]], grad_fn=<AddmmBackward0>)
<class 'torch.nn.modules.container.Sequential'>
Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)


### 1.2 state_dict() --OrderedDict

In [12]:
print(net.state_dict())
print(net[0].state_dict())
print(net[0].bias)
print(net[0].bias.data)
print(net[0].weight.data)

OrderedDict([('0.weight', tensor([[ 0.0935,  0.1801,  0.1187, -0.3249],
        [ 0.2076,  0.0274,  0.4316, -0.0249],
        [ 0.2735, -0.3846,  0.4774, -0.1125],
        [ 0.2064,  0.0798, -0.0143,  0.0393],
        [-0.1479, -0.0265, -0.2732,  0.1915],
        [-0.4145,  0.0806,  0.0904,  0.3117],
        [ 0.4089,  0.1787,  0.2306,  0.2903],
        [ 0.0788,  0.1531,  0.0881,  0.3275]])), ('0.bias', tensor([-0.2397,  0.4770,  0.4311,  0.3510, -0.0668, -0.2438,  0.2393, -0.4151])), ('2.weight', tensor([[ 0.3281,  0.0088, -0.2057,  0.0403, -0.3187,  0.2523, -0.2307,  0.3026]])), ('2.bias', tensor([0.0284]))])
OrderedDict([('weight', tensor([[ 0.0935,  0.1801,  0.1187, -0.3249],
        [ 0.2076,  0.0274,  0.4316, -0.0249],
        [ 0.2735, -0.3846,  0.4774, -0.1125],
        [ 0.2064,  0.0798, -0.0143,  0.0393],
        [-0.1479, -0.0265, -0.2732,  0.1915],
        [-0.4145,  0.0806,  0.0904,  0.3117],
        [ 0.4089,  0.1787,  0.2306,  0.2903],
        [ 0.0788,  0.1531,  0.0881

### 1.3 named_parameters()

In [17]:
print(type(net[0].named_parameters()))
print([(name, param.shape) for name, param in net.named_parameters()])
print([(name, param.shape) for name, param in net[0].named_parameters()])

params = list(net.named_parameters())
print(params.__len__())
print([params[i] for i in range(params.__len__())])


<class 'generator'>
[('0.weight', torch.Size([8, 4])), ('0.bias', torch.Size([8])), ('2.weight', torch.Size([1, 8])), ('2.bias', torch.Size([1]))]
[('weight', torch.Size([8, 4])), ('bias', torch.Size([8]))]
4
[('0.weight', Parameter containing:
tensor([[ 0.0935,  0.1801,  0.1187, -0.3249],
        [ 0.2076,  0.0274,  0.4316, -0.0249],
        [ 0.2735, -0.3846,  0.4774, -0.1125],
        [ 0.2064,  0.0798, -0.0143,  0.0393],
        [-0.1479, -0.0265, -0.2732,  0.1915],
        [-0.4145,  0.0806,  0.0904,  0.3117],
        [ 0.4089,  0.1787,  0.2306,  0.2903],
        [ 0.0788,  0.1531,  0.0881,  0.3275]], requires_grad=True)), ('0.bias', Parameter containing:
tensor([-0.2397,  0.4770,  0.4311,  0.3510, -0.0668, -0.2438,  0.2393, -0.4151],
       requires_grad=True)), ('2.weight', Parameter containing:
tensor([[ 0.3281,  0.0088, -0.2057,  0.0403, -0.3187,  0.2523, -0.2307,  0.3026]],
       requires_grad=True)), ('2.bias', Parameter containing:
tensor([0.0284], requires_grad=True))]


### 1.4 net block()

In [24]:
def block1():
    return nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                         nn.Linear(8, 4), nn.ReLU())

def block2():
    net = nn.Sequential()
    for i in range(4):
        # 在这里嵌套
        net.add_module(f'block {i}', block1())
    return net

rgnet = nn.Sequential(block2(), nn.Linear(4, 1))
rgnet(X)
print(rgnet)
print(rgnet[0][1][0].weight)



Sequential(
  (0): Sequential(
    (block 0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.4340, -0.3095,  0.1278, -0.2557],
        [-0.3289, -0.0671, -0.2499, -0.4294],
        [ 0.3432, -0.1627, -0.4337,  

## 2、参数初始化

### 2.1 整体初始化

In [ ]:
def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean=0, std=0.01)
        nn.init.zeros_(m.bias)
net.apply(init_normal)
print(net[0].weight.data[0], net[0].bias.data[0])

def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 1)
        nn.init.zeros_(m.bias)
net.apply(init_constant)
print(net[0].weight.data[0], net[0].bias.data[0])

### 2.2 分块初始化

In [28]:
def init_xavier(m):
    if type(m) == nn.Linear:
        nn.init.xavier_uniform_(m.weight)
def init_42(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 42)

net[0].apply(init_xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data)

tensor([-0.1683,  0.0429, -0.1990, -0.0411])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


### 2.3 自定义初始化

In [ ]:
def my_init(m):
    if type(m) == nn.Linear:
        print("Init", *[(name, param.shape)
                        for name, param in m.named_parameters()][0])
        nn.init.uniform_(m.weight, -10, 10)
        m.weight.data *= (m.weight.data.abs() >= 5)

net.apply(my_init)
print(net[0].weight[:2])

net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
print(net[0].weight.data[0])


### 2.4 参数绑定

In [29]:
# 我们需要给共享层一个名称，以便可以引用它的参数
shared = nn.Linear(8, 8)
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.Linear(8, 1))
net(X)
# 检查参数是否相同
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
# 确保它们实际上是同一个对象，而不只是有相同的值
print(net[2].weight.data[0] == net[4].weight.data[0])


tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])


## 3、自定义层

## 3.1 无参数自定义层

In [31]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
print(layer(torch.FloatTensor([1, 2, 3, 4, 5])))

net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
print(Y.mean())


tensor([-2., -1.,  0.,  1.,  2.])


tensor(2.7940e-09, grad_fn=<MeanBackward0>)

## 3.1 无参数自定义层

In [34]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
print(linear.weight)
print(linear(torch.rand(2, 5)))

net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
print(net(torch.rand(2, 64)))



Parameter containing:
tensor([[ 1.1331e+00,  1.2278e+00,  1.2990e-01],
        [ 1.3874e-03,  5.1289e-01,  1.7030e+00],
        [-1.0082e+00,  1.8983e-01, -3.0458e-01],
        [-1.4345e+00,  8.2401e-01,  3.3082e-01],
        [-1.1291e-01,  2.6366e-01, -7.0554e-01]], requires_grad=True)
tensor([[0.0000, 0.0000, 2.7243],
        [0.0000, 0.2714, 2.4663]])
tensor([[0.],
        [0.]])


## 4、读写文件

### 4.1 保存和加载张量

In [35]:
x = torch.arange(4)
torch.save(x, 'x-file')
x2 = torch.load('x-file')
print(x2)

y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
print((x2, y2))

mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
print(mydict2)


tensor([0, 1, 2, 3])


### 4.2 保存和加载模型参数

In [36]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)
torch.save(net.state_dict(), 'mlp.params')

clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])